#service:
#  hostname:
#    discovery: 192.168.196.207
#    mysql: ${MYSQL_HOST:192.168.196.207}

spring:
  application:
    name: auth-service
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddlAuto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop_iphone?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: ENC(hQgsVftACv7iHT9Vdtbw0s32fTgZcS5y)
server:
  port: 8800

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
#      defaultZone: http://${service.hostname.discovery}:8761/eureka/
security:
  oauth2:
    client:
      clientId: client
      clientSecret: ENC(48mMvLaMDImeOJFUE/DT0ufm7y9Rcdn/)
      accessTokenValiditySeconds: 5000000
      refreshTokenValiditySeconds: 18000
encrypt:
  keyStore:
    alias: jwt
    password: ENC(TQVu0i9dxQgQDOo19OSnKg==)
