spring:
  application:
    name: auth-service
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddlAuto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:shop_iphone}?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: admin
server:
  port: 3001

eureka:
  client:
  serviceUrl:
    defaultZone: http://localhost:8888/eureka/

security:
  oauth2:
    client:
      clientId: client
      clientSecret: client@2022
      accessTokenValiditySeconds: 18000
      refreshTokenValiditySeconds: 18000
encrypt:
  keyStore:
    alias: jwt
    password: god@123