spring:
  application:
    name: discovery

#eureka:
#  instance:
#    hostname: 192.168.196.207
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
#      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
server:
  port: 8888
